# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binary_trie.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62inary_trie.proto\"O\n\x0e\x42inaryTrieNode\x12\x0e\n\x06is_end\x18\x01 \x01(\x08\x12\x16\n\x0ehas_zero_child\x18\x02 \x01(\x08\x12\x15\n\rhas_one_child\x18\x03 \x01(\x08\"1\n\x0f\x42inaryTrieNodes\x12\x1e\n\x05nodes\x18\x01 \x03(\x0b\x32\x0f.BinaryTrieNodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'binary_trie_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BINARYTRIENODE']._serialized_start=21
  _globals['_BINARYTRIENODE']._serialized_end=100
  _globals['_BINARYTRIENODES']._serialized_start=102
  _globals['_BINARYTRIENODES']._serialized_end=151
# @@protoc_insertion_point(module_scope)
