# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trie.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntrie.proto\"\x95\x01\n\x0e\x42inaryTrieNode\x12\x0e\n\x06is_end\x18\x01 \x01(\x08\x12*\n\x08\x63hildren\x18\x02 \x01(\x0b\x32\x18.BinaryTrieNode.Children\x1aG\n\x08\x43hildren\x12\x1d\n\x04zero\x18\x01 \x01(\x0b\x32\x0f.BinaryTrieNode\x12\x1c\n\x03one\x18\x02 \x01(\x0b\x32\x0f.BinaryTrieNodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trie_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BINARYTRIENODE']._serialized_start=15
  _globals['_BINARYTRIENODE']._serialized_end=164
  _globals['_BINARYTRIENODE_CHILDREN']._serialized_start=93
  _globals['_BINARYTRIENODE_CHILDREN']._serialized_end=164
# @@protoc_insertion_point(module_scope)
